version: '3'
services:
  nginx:
    build: .
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - C:/Certbot:/etc/letsencrypt
    restart: unless-stopped